### ISSUE TITLE
deployment fails

### ISSUE THREAD

**Issue by dwehrmann** [McFoggy/TodoOnFire#6]
done all the steps in the readme, downgraded node to v. 6.11.1  (npm Install did not succeed before that). When deploying, this error pops up:

⚠  functions[slashTodo(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
**Detailed stack trace: Error: Invalid Firebase app options passed as the first argument to initializeApp() for the app named "[DEFAULT]". The "credential" property must be an object which implements the Credential interface.**
    at FirebaseAppError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/srv/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at new FirebaseApp (/srv/node_modules/firebase-admin/lib/firebase-app.js:200:19)
    at FirebaseNamespaceInternals.initializeApp (/srv/node_modules/firebase-admin/lib/firebase-namespace.js:64:19)
    at FirebaseNamespace.initializeApp (/srv/node_modules/firebase-admin/lib/firebase-namespace.js:259:30)
    at Object.<anonymous> (/srv/index.js:10:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

and 

⚠  functions[todoClose(us-central1)]: Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: Invalid Firebase app options passed as the first argument to **initializeApp() for the app named "[DEFAULT]". The "credential" property must be an object which implements the Credential interface.**
    at FirebaseAppError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAppError (/srv/node_modules/firebase-admin/lib/utils/error.js:119:28)
    at new FirebaseApp (/srv/node_modules/firebase-admin/lib/firebase-app.js:200:19)
    at FirebaseNamespaceInternals.initializeApp (/srv/node_modules/firebase-admin/lib/firebase-namespace.js:64:19)
    at FirebaseNamespace.initializeApp (/srv/node_modules/firebase-admin/lib/firebase-namespace.js:259:30)
    at Object.<anonymous> (/srv/index.js:10:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

any clues? I'd really like to get this working ...

**Comment by dwehrmann** [comment]
`npm install -g firebase-tools@latest`
`npm install firebase-functions@latest`
`npm install firebase-admin@latest`

helped. Functions were deployed properly now.

**Comment by McFoggy** [comment]
Great to see that you found a solution, thanks for reporting it for others.
